/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleExample;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.insertNewItem(connection, id, Author, Manufacturer, Width, Height, KItId);());
//    }
}
