/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleExample;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Library {
	public static void insertNewItem(Connection connection, int id, String Author, String Manufacturer, Double Width,
			Double Height, int KItId) throws SQLException {
		String query = "INSERT INTO Item VALUES( ?, ?, ?, ?, ?, ?)";

		PreparedStatement preparedStatement = connection.prepareStatement(query);
		preparedStatement.setInt(1, id);
		preparedStatement.setString(2, Author);
		preparedStatement.setString(3, Manufacturer);
		preparedStatement.setDouble(4, Width);
		preparedStatement.setDouble(5, Height);
		preparedStatement.setInt(6, KItId);

		preparedStatement.executeUpdate();
		System.out.println("The item has been inserted successfully");

	}
	public static Connection connectToDB() throws ClassNotFoundException {
		// load and register JDBC driver for MySQL
		Class.forName("com.mysql.cj.jdbc.Driver");
		Connection connection = null;
		try {
			connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/STORE", "root", "ya33");
			System.out.println("Connected With the database successfully");

		} catch (SQLException e) {
			System.out.println("Error while connecting to the database");
			System.out.println(e.toString());
		}
		return connection;
	}
	
	public static void main(String[] args) throws ClassNotFoundException, SQLException {
		Connection conn = connectToDB();
		insertNewItem(conn, 20, "asasa", "sdsds", 2.9, 3.8, 1);
		
	}
}
